name: Trufflehog
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@36f6f697079e637bccb1e05561a481d8b4016862
        with:
          path: ./
          base_depth: 1
